### ISSUE TITLE
disable battery optimization directly from app

### ISSUE THREAD

**Issue by mehrdad-shokri** [SachinGanesh/battery_optimization#3]
You can also fire intent `ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` for opening a dialog to disable battery optimization without opening the settings page. I can send a PR to add this method. please answer this issue to confirm you would consider this PR.

**Comment by SachinGanesh** [comment]
We did explore this option. But there is a chance that the app might get suspended for using the above intent

https://developer.android.com/training/monitoring-device-state/doze-standby#whitelisting-cases

**"Note: Google Play policies prohibit apps from requesting direct exemption from Power Management features in Android 6.0+ (Doze and App Standby) unless the core function of the app is adversely affected."**

**Comment by mehrdad-shokri** [comment]
I think you can add this method to the package and inform the developer of this incident.

**Comment by mehrdad-shokri** [comment]
There are valid use cases that Google Play will consider valid. https://developer.android.com/training/monitoring-device-state/doze-standby#exemption-cases
